version: '3.8'
services:

  web:
    image: php:8.0-apache
    volumes:
      - ./application:/var/www/html
    ports:
      - "80:80"
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - "PMA_HOST=db"
      - "PMA_PORT=3306"
